### ISSUE TITLE
PrePARE 3.2.3: exception "no attribute variable_id"

### ISSUE THREAD

**Issue by cehbrecht** [PCMDI/cmor#163]
i've tried ``PrePARE`` from the new cmor release 3.2.3 with a test file (cordex, cmip5) and got this exception:

```
$ PrePARE Tables/CMIP6_CV.json pr_Amon_MPI-ESM-LR_historical_r1i1p1_185001-200512.nc 
Traceback (most recent call last):
  File "/home/pingu/.conda/envs/cmor/bin/PrePARE", line 11, in <module>
    load_entry_point('CMOR==3.2', 'console_scripts', 'PrePARE')()
  File "/home/pingu/.conda/envs/cmor/lib/python2.7/site-packages/cmip6_cv/PrePARE/PrePARE.py", line 370, in main
    process = checkCMIP6(args)
  File "/home/pingu/.conda/envs/cmor/lib/python2.7/site-packages/cmip6_cv/PrePARE/PrePARE.py", line 132, in __init__
    self.var = [self.infile.variable_id]
AttributeError: 'CdmsFile' object has no attribute 'variable_id'
```

This worked in the previous version.

**Comment by dnadeau4** [comment]
@cehbrecht `PrePARE` messages could be better I agree.  You can try to pass the `--variable` option and see what happens.  I never try to any other file than CMIP6.  You will have a lot of message on the screen similar to a compiler.  :smirk: 
```
usage: PrePARE [-h] [--variable VARIABLE] cmip6_table infile [outfile]
```

**Comment by dnadeau4** [comment]
@cehbrecht Did `--variable` worked for you?

**Comment by cehbrecht** [comment]
forget to check ... here it is now:

```
$ PrePARE --variable pr cmip6-cmor-tables/Tables/CMIP6_CV.json ~/Desktop/pr_Amon_MPI-ESM-LR_historical_r1i1p1_185001-200512.nc 
Traceback (most recent call last):
  File "/home/pingu/.conda/envs/qa/bin/PrePARE", line 11, in <module>
    load_entry_point('CMOR==3.2', 'console_scripts', 'PrePARE')()
  File "/home/pingu/.conda/envs/qa/lib/python2.7/site-packages/cmip6_cv/PrePARE/PrePARE.py", line 370, in main
    process = checkCMIP6(args)
  File "/home/pingu/.conda/envs/qa/lib/python2.7/site-packages/cmip6_cv/PrePARE/PrePARE.py", line 178, in __init__
    if(self.dictGbl["sub_experiment_id"] not in ["none"]):
KeyError: 'sub_experiment_id'
```

Using the same cmip5 file as input and with variable `pr` ... missing now `sub_experiment_id`.

**Comment by dnadeau4** [comment]
I was able to make PrePARE work with `CMIP5`  by changing this section: 

The output is **_unreal_**, but it was nice to see how much work I put in `CMIP6`. 😄 

PrePARE.py:200
```python
        member_id = ""
        if(["sub_experiment_id"] in self.dictGbl.keys() ):
                if(self.dictGbl["sub_experiment_id"] not in ["none"]):
                    member_id = self.dictGbl["sub_experiment_id"] + \
                        '-' + self.dictGbl["variant_label"]
                else:
                    member_id = self.dictGbl["variant_label"]
```

**Comment by dnadeau4** [comment]
I put this in 3.2.5.  Note that the first line should be
```Python
        if("sub_experiment_id" in self.dictGbl.keys() ):
```
