### ISSUE TITLE
CMOR 3.2.5 not compatible with version 01.00.12 of the MIP tables

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#214]
The code in [Test/jamie_hybrid_height.py](https://github.com/PCMDI/cmor/blob/master/Test/jamie_hybrid_height.py) completes successfully using CMOR 3.2.4 and version `01.00.12` of the MIP tables. However, CMOR 3.2.5 and version `01.00.12` of the MIP tables raises an exception:

```
% ./example.py 
cmor.axis calls complete
Traceback (most recent call last):
  File "./example.py", line 54, in <module>
    main1()
  File "./example.py", line 40, in main1
    'd', [0., 0.5], [[0., 0.25], [0.25, 1.]])
  File "/home/h03/support/software/cmor-3.2.5/lib/python2.7/site-packages/CMOR-3.2-py2.7-linux-x86_64.egg/cmor/pywrapper.py", line 644, in zfactor
    ndims, axis_ids, type, zfactor_values, zfactor_bounds)
_cmor.CMORError: Problem with 'cmor.zfactor'. Please check the logfile (if defined).
```

The log file contains:

```
C Traceback:
! In function: cmor_variable
! called from: cmor_zfactor
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Could not find a matching variable for name: 'b'
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: cmor_variable
! called from: cmor_zfactor
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You defined variable '' (table 6hrLev) with axis id 'hybrid_height' which is not part of this variable acco
rding to your table, it says: ( )
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: cmor_variable
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Could not find a matching variable for name: 'b_bnds'
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: cmor_variable
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You defined variable '' (table 6hrLev) with axis id 'hybrid_height' which is not part of this variable according to your table, it says: ( )
!
!!!!!!!!!!!!!!!!!!!!!!!!!

```
CMOR 3.2.5 and version `01.00.13` of the MIP tables also raises an exception:

```
% ./example.py 
cmor.axis calls complete
cmor.zfactor calls complete
cmor.variable call complete
Traceback (most recent call last):
  File "./example.py", line 54, in <module>
    main1()
  File "./example.py", line 47, in main1
    cmor.write(varid, values, time_vals=[6.0], time_bnds=[3., 12.])
  File "/home/h03/support/software/cmor-3.2.5/lib/python2.7/site-packages/CMOR-3.2-py2.7-linux-x86_64.egg/cmor/pywrapper.py", line 795, in write
    time_vals, time_bnds, store_with)
_cmor.CMORError: Problem with 'cmor.write'. Please check the logfile (if defined).
```

The log file contains:

```
C Traceback:
! In function: _CV_ValidateAttribute
! called from: _CV_checkGblAttributes
! called from: cmor_write
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: The attribute "further_info_url" could not be validated. 
! The current input value is "http://furtherinfo.es-doc.org/CMIP6.PCMDI.PCMDI-test-1-0.piControl-withism.none.r11i1p
1f1" which is not valid 
! Valid values must match the regular expression:
! 	["^http://furtherinfo.es-doc.org/[[:alpha:]]\{1,\}$"  ...] 
! 
! Check your Control Vocabulary file "/project/cdds/etc/mip_tables/CMIP6/01.00.13//CMIP6_CV.json".
! 
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: _CV_checkGblAttributes
! called from: cmor_write
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Please fix required attributes mentioned in
! the warnings/error above and rerun. (aborting!)
! 
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Cannot continue until you fix the errors listed above: -1
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

There are two issues here:

1) It is not clear from the [3.2.5 release notes](https://github.com/PCMDI/cmor/releases/tag/CMOR-3.2.5) that compatibility with MIP tables older than `01.00.13` is broken (see, e.g. the message provided in the [3.2.4 release notes](https://github.com/PCMDI/cmor/releases/tag/CMOR-3.2.4)).

2) CMOR 3.2.5 appears to construct the `further_info_url` internally (it is not defined in the [common_user_input.json](https://github.com/PCMDI/cmor/blob/master/Test/common_user_input.json)), but the regular expression doesn't allow `.` (`[:alpha:]` is equivalent to `[a-zA-Z]`).

Would it be possible to resolve these issues, please?

(cc @jonseddon)

**Comment by dnadeau4** [comment]
Fix with #219
