### ISSUE TITLE
Correctly defining climatological time_bounds

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#297]
I'm trying to generate a time axis for a climatological average variable which extends from `1955-01-01` to `2012-12-31`, I have a valid time axis:
```
In [92]: times
Out[92]: 
[10606.500000 days since 1955-1-1, # 1984-1-15 12:0:0
 10636.500000 days since 1955-1-1,
 10666.500000 days since 1955-1-1,
 10697.000000 days since 1955-1-1,
 10727.500000 days since 1955-1-1,
 10758.000000 days since 1955-1-1,
 10788.500000 days since 1955-1-1,
 10819.500000 days since 1955-1-1,
 10850.000000 days since 1955-1-1,
 10880.500000 days since 1955-1-1,
 10911.000000 days since 1955-1-1,
 10941.500000 days since 1955-1-1]
```
And I have what I thought was a valid time_bounds:
```
In [94]: times_bnds
Out[94]: 
[[0.000000 days since 1955-1-1, 20849.541655 days since 1955-1-1], # 1955-1-1 0:0:0, 2012-1-31 12:59:59
 [31.000000 days since 1955-1-1, 20878.541655 days since 1955-1-1],
 [59.000000 days since 1955-1-1, 20909.541655 days since 1955-1-1],
 [90.000000 days since 1955-1-1, 20939.541655 days since 1955-1-1],
 [120.000000 days since 1955-1-1, 20970.541655 days since 1955-1-1],
 [151.000000 days since 1955-1-1, 21000.541655 days since 1955-1-1],
 [181.000000 days since 1955-1-1, 21031.541655 days since 1955-1-1],
 [212.000000 days since 1955-1-1, 21062.541655 days since 1955-1-1],
 [243.000000 days since 1955-1-1, 21092.541655 days since 1955-1-1],
 [273.000000 days since 1955-1-1, 21123.541655 days since 1955-1-1],
 [304.000000 days since 1955-1-1, 21153.541655 days since 1955-1-1],
 [334.000000 days since 1955-1-1, 21184.541655 days since 1955-1-1]]
```
However I am getting the following error from CMOR3.3.0:
```
Start CMOR write..
Traceback (most recent call last):
  File "runCmorDemo.py", line 255, in <module>
    cmor.write(varid,values,time_vals=time,time_bnds=time.getBounds()) ; # Write variable with time axis
  File "/export/duro/anaconda2/envs/cmorNightly180201/lib/python2.7/site-packages/cmor/pywrapper.py", line 766, in write
    _check_time_bounds_contiguous(time_bnds)
  File "/export/duro/anaconda2/envs/cmorNightly180201/lib/python2.7/site-packages/cmor/pywrapper.py", line 810, in _check_time_bounds_contiguous
    raise Exception("error time_bnds have gaps between them")
Exception: error time_bnds have gaps between them
```
@dnadeau4 @taylor13 do you have any tips for me?

PCMDI/input4MIPs-cmor-tables#30

**Comment by durack1** [comment]
I get the same error if I attempt to set the beginning of the following month as the start and end bounds:
```
In [99]: times_bnds
Out[99]: 
[[1955-1-1 0:0:0.0, 2012-2-1 0:0:0.0],
 [1955-2-1 0:0:0.0, 2012-3-1 0:0:0.0],
 [1955-3-1 0:0:0.0, 2012-4-1 0:0:0.0],
 [1955-4-1 0:0:0.0, 2012-5-1 0:0:0.0],
 [1955-5-1 0:0:0.0, 2012-6-1 0:0:0.0],
 [1955-6-1 0:0:0.0, 2012-7-1 0:0:0.0],
 [1955-7-1 0:0:0.0, 2012-8-1 0:0:0.0],
 [1955-8-1 0:0:0.0, 2012-9-1 0:0:0.0],
 [1955-9-1 0:0:0.0, 2012-10-1 0:0:0.0],
 [1955-10-1 0:0:0.0, 2012-11-1 0:0:0.0],
 [1955-11-1 0:0:0.0, 2012-12-1 0:0:0.0],
 [1955-12-1 0:0:0.0, 2013-1-1 0:0:0.0]]
```

**Comment by taylor13** [comment]
I think there is a bug in CMOR/PrePARe.  See https://github.com/PCMDI/cmor/issues/287 and also check https://github.com/PCMDI/cmor/issues/283.

**Comment by durack1** [comment]
@dnadeau4 some success:
```
key,var: OmonC s_u10a
filePath: ../180125/woa13_decav_s_0-10m.mon_01v2_filled.nc
cmorTable: input4MIPs-cmor-tables/Tables/input4MIPs_OmonC.json
inputVarName: s_u10a
outputVarName: sos
outputUnits: 0.001
Source data read start..
/export/durack1/anaconda2/envs/cmorNightly180213/lib/python2.7/site-packages/cdms2/axis.py:1617: UserWarning:
Your first bounds[0,0] -180.000000000000000 will be corrected to -180.000000000000000
Your bounds bounds[-1,1] 180.000000000000000 will be corrected to 180.000000000000000
  warnings.warn(msg, UserWarning)
Source data read end..
Start CMORizing..
Traceback (most recent call last):
  File "runCmorDemo.py", line 239, in <module>
    axisId = cmor.axis(**axis)
  File "/export/durack1/anaconda2/envs/cmorNightly180213/lib/python2.7/site-packages/cmor/pywrapper.py", line 428, in axis
    cell_bounds = cell_bounds.astype(type)
TypeError: float() argument must be a string or a number
```

**Comment by durack1** [comment]
And this is the `axis` being passed that is causing the problem:
```
axis:  {'units': 'days since 1955-01-01 0.0.0', 'coord_vals':    id: time
   Designated a time axis.
   units:  days since 1955-01-01 0.0.0
   Length: 12
   First:  10606.5
   Last:   10941.5
   Python id:  0x7f3448ac5f10
, 'table_entry': 'time2'}
Traceback (most recent call last):
  File "runCmorDemo.py", line 242, in <module>
    axisId = cmor.axis(**axis)
  File "/export/duro/anaconda2/envs/cmorNightly180213/lib/python2.7/site-packages/cmor/pywrapper.py", line 428, in axis
    cell_bounds = cell_bounds.astype(type)
TypeError: float() argument must be a string or a number
```

**Comment by durack1** [comment]
@dnadeau4 ouch, another segfault:
```
Start CMORizing..                                                                                                              
axis:  {'units': 'days since 1955-01-01 0.0.0', 'coord_vals':    id: time                                                      
   Designated a time axis.                                                                                                     
   units:  days since 1955-01-01 0.0.0                                                                                         
   Length: 12                                                                                                                  
   First:  10606.5                                                                                                             
   Last:   10941.5                                                                                                             
   Python id:  0x7fe402b02dd0                                                                                                  
, 'table_entry': 'time2'}                                                                                                      
axis:  {'units': 'degrees_north', 'coord_vals': array([-89.875, -89.625, -89.375, -89.125, -88.875, -88.625, -88.375,          
       -88.125, -87.875, -87.625, -87.375, -87.125, -86.875, -86.625,                                                          
...
        86.875,  87.125,  87.375,  87.625,  87.875,  88.125,  88.375,
        88.625,  88.875,  89.125,  89.375,  89.625,  89.875], dtype=float32), 'table_entry': 'latitude', 'cell_bounds': array([[-90.  , -89.75],
       [-89.75, -89.5 ],
       [-89.5 , -89.25],
       ...,
       [ 89.25,  89.5 ],
       [ 89.5 ,  89.75],
       [ 89.75,  90.  ]])}
axis:  {'units': 'degrees_east', 'coord_vals': array([-179.875, -179.625, -179.375, ...,  179.375,  179.625,  179.875], dtype=float32), 'table_entry': 'longitude', 'cell_bounds': array([[-180.  , -179.75],
       [-179.75, -179.5 ],
       [-179.5 , -179.25],
       ...,
       [ 179.25,  179.5 ],
       [ 179.5 ,  179.75],
       [ 179.75,  180.  ]])}
d.shape: (5, 720, 1440)
outputVarName: sos
d.units: 1
d.missing: -9.99e+33
Start CMOR write..

C Traceback:
In function: _CV_checkSourceID
! called from: cmor_setGblAttr
! called from: cmor_write
!
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: You did not define a source section in your source_id MRI-JRA55-do-1-3.
!
! See Control Vocabulary JSON file. (input4MIPs-cmor-tables/Tables/input4MIPs_CV.json)
!
!!!!!!!!!!!!!!!!!!!!!!!!!
Segmentation fault (core dumped)
```

**Comment by durack1** [comment]
@dnadeau4 I've found some other weird behaviors (ignore the `source_id` error, I have to clean up my inputs) that would be great to be fixed, the `segfault` above, and this weird error:
```
Start CMOR write..                                                                                                             
C Traceback:
In function: _CV_checkSourceID                                                                                                 
! called from: cmor_setGblAttr                                                                                                 
! called from: cmor_write                                                                                                      
!                                                                                                                              
!!!!!!!!!!!!!!!!!!!!!!!!!
!                                                                                                                              
! Warning: You did not define a source section in your source_id MRI-JRA55-do-1-3.                                             
!                                                                                                                              
!                                                                                                                              
! See Control Vocabulary JSON file. (input4MIPs-cmor-tables/Tables/input4MIPs_CV.json)                                         
!                                                                                                                              
!                                                                                                                              
!!!!!!!!!!!!!!!!!!!!!!!!!                                                                                                      
C Traceback:
! In function: cmor_write_var_to_file                                                                                          
!                                                                                                                                
!!!!!!!!!!!!!!!!!!!!!!!!!
!                                                                                                                              
! Error: variable 'sos' (table input4MIPs_OmonC) you are passing time values but you already defined them via cmor_axis, this is not allowed                                                                                                                  
!                                                                                                                              
!!!!!!!!!!!!!!!!!!!!!!!!!

```

**Comment by taylor13** [comment]
As I recall, you can either define the time axis values when you define the time axis, or you can pass the time values when you write the data, but you can't do both.  Would that explain it?

**Comment by durack1** [comment]
@taylor13 thanks for clarifying, if that is indeed the case then I think we need to catch this with an appropriate error message. Oh, and we also need to ascertain what is causing the segfault and deal with that better too

**Comment by taylor13** [comment]
How would you improve upon: "! Error: variable 'sos' (table input4MIPs_OmonC) you are passing time values but you already defined them via cmor_axis, this is not allowed".

Note that the CMOR documentation (https://cmor.llnl.gov/mydoc_cmor3_api/) of cmor_write says about the time_vals argument: "This argument should appear only if the time coordinate values were not passed in defining the time axis (i.e., in calling cmor_axis). "

**Comment by taylor13** [comment]
As for the segfault, if fixing whatever causes the warning "! Warning: You did not define a source section in your source_id MRI-JRA55-do-1-3." eliminates the segfault, then I think that's probably good enough for now.  As soon as a user encounters the segfault, he/she should first eliminate the warnings, and then be good to go.

**Comment by durack1** [comment]
The segfault is no longer due to the bad source_id definition, rather it's with bad info passed to cmor, but it would be better to catch all segfaults if we can..

**Comment by taylor13** [comment]
I agree. thanks.

**Comment by dnadeau4** [comment]
@durack1 can you close this issue and open a new one with the `bad info passed to cmor`.  If you can give me some bad code too 😏 that would help.

**Comment by durack1** [comment]
This issue is resolved, however the segfault is not (https://github.com/PCMDI/cmor/issues/297#issuecomment-365391642) so will open a new issue
