### ISSUE TITLE
PrePARE requires 

### ISSUE THREAD

**Issue by jonseddon** [PCMDI/cmor#317]
Hi,

According to version 6.2.6 of https://goo.gl/v1drZl then if there is no parent then it is preferred if `branch_time_in_child` and `branch_time_in_parent` are omitted, or set to `no_parent`. At the moment, either of these will result in a KeyError:

```
$ ncatted -a branch_time_in_child,global,d,, tas_Amon_HadGEM3-GC31-LM_highresSST-present_r1i1p1f1_gn_195001-195012.nc
$ PrePARE Tables/CMIP6_Amon.json tas_Amon_HadGEM3-GC31-LM_highresSST-present_r1i1p1f1_gn_195001-195012.nc 
Processing: /.../tas_Amon_HadGEM3-GC31-LM_highresSST-present_r1i1p1f1_gn_195001-195012.nc

Traceback (most recent call last):
  File "/.../envs/cmor/bin/PrePARE", line 11, in <module>
    load_entry_point('CMOR==3.3', 'console_scripts', 'PrePARE')()
  File "/.../envs/cmor/lib/python2.7/site-packages/cmip6_cv/PrePARE/PrePARE.py", line 724, in main
    sequential_process(source)
  File "/.../envs/cmor/lib/python2.7/site-packages/cmip6_cv/PrePARE/PrePARE.py", line 633, in sequential_process
    checker.ControlVocab(ncfile)
  File "/.../envs/cmor/lib/python2.7/site-packages/cmip6_cv/PrePARE/PrePARE.py", line 469, in ControlVocab
    if not isinstance(self.dictGbl['branch_time_in_child'], numpy.float64):
KeyError: 'branch_time_in_child'

```

Thanks,

Jon

**Comment by dnadeau4** [comment]
I fixed that in the PrePARE branch.  https://github.com/PCMDI/cmor/blob/PrePARE/LibCV/PrePARE/PrePARE.py#L469-L485

**Comment by durack1** [comment]
@dnadeau4 should this be tagged against `3.3.2` and reopened until that is released?

**Comment by jonseddon** [comment]
@dnadeau4 @durack1 The global attributes document (https://goo.gl/v1drZl) says that the string "no parent" is also a valid value for these attributes.
