### ISSUE TITLE
Python error handling no longer works on master

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#385]
Hi @doutriaux1, @taylor13,

I was attempting to follow up with #245 by running some tests with master and I realised that the Python error handling I introduced in #86 no longer works; now when I run CMOR, instead of seeing, e.g.

```
Traceback (most recent call last):
  File "./example.py", line 43, in main
    cmor.write(var_id, data[i:i])
  File "/cmor/lib/python2.7/site-packages/CMOR-3.3-py2.7-linux-x86_64.egg/cmor/pywrapper.py", line 800, in write
    time_vals, time_bnds, store_with)
_cmor.CMORError: Problem with 'cmor.write'. Please check the logfile (if defined).
```

(from CMOR 3.3.0), I now see:

```
Traceback (most recent call last):
  File "./example.py", line 43, in main
    cmor.write(var_id, data[i:i])
  File "/cmor/lib/python2.7/site-packages/CMOR-3.3.3-py2.7-linux-x86_64.egg/cmor/pywrapper.py", line 817, in write
    time_vals, time_bnds, store_with)
KeyboardInterrupt
```

which was exactly the issue I was trying to avoid!

In #374 @doutriaux1 [mentioned](https://github.com/PCMDI/cmor/issues/374#issuecomment-408886577) that a change was necessary for Fortran to exit nicely. Would it be possible to fix the Fortran issue without affecting the way the Python error handling works, please? :)

**Comment by doutriaux1** [comment]
@ehogan unfortunately it was not possible to do it any other way. For now just trap your code with a `try/except KeyboardInterupt` statement.

**Comment by matthew-mizielinski** [comment]
Sorry @doutriaux1, this isn't acceptable -- we won't be able to pick up a version of CMOR where it looks like the user hit Ctrl-C when something goes wrong with in the `cmor.write` step. 

We rely on messages such as the `_cmor.CMORError` to allow us to catch where things have gone wrong with the processing of a variable among sets of hundreds of variables. Any change to this sort of behaviour as we build up to starting processing and submission of data from the UK models (HadGEM3 & UKESM1) in September is too disruptive.

@ehogan put a some effort into getting CMOR to throw exceptions in a way that we can handle in #86 nearly two years ago, and we cannot go back on this now.

Please reconsider the changes that have lead to this change in behaviour.

**Comment by doutriaux1** [comment]
@matthew-mizielinski I see your point, I'll look into this further, maybe separate behavior for Fortran.

**Comment by doutriaux1** [comment]
@matthew-mizielinski but it's not really disturbive, simply change
```python
try:
  [something cmor]
except:
  [blah]
```
to
```python
try:
  [something cmor]
except (
Exception, KeyboardInterrupt):
  [blah]
```

**Comment by doutriaux1** [comment]
@matthew-mizielinski @ehogan ok I addressed this in https://github.com/PCMDI/cmor/pull/387

The idea is that C and Python revert to SIGTERM by default and Fortran stays with SIGINT for default

While at it I add a few function to let the user set the `terminate` signal to whatever signal is desired.

**Comment by taylor13** [comment]
If @matthew-mizielinski and @ehogan are happy, it's fine with me. Perhaps Emma could test it before we do the next release.

**Comment by doutriaux1** [comment]
@ehoganI added the install from source instructions at: https://cmor.llnl.gov/mydoc_cmor3_github/

**Comment by doutriaux1** [comment]
@ehogan I added the install from source instructions at: https://cmor.llnl.gov/mydoc_cmor3_github/

**Comment by ehogan** [comment]
Many thanks @doutriaux1 @taylor13 for fixing this issue; it is very much appreciated :) I'm more than happy to test this once the branch has been merged into master :)

**Comment by doutriaux1** [comment]
@ehogan it would be preferable to test before it's in master though!

**Comment by ehogan** [comment]
No problem :)

**Comment by ehogan** [comment]
Everything looks good to me! Thank you very much! :D

**Comment by matthew-mizielinski** [comment]
@doutriaux1, can I add my thanks to @ehogan's, we really appreciate you fixing this.
