### ISSUE TITLE
Dependency problem when building MacOS nightly build

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/cmor#451]
CircleCI is having an issue stemming from libgfortran dependencies when making the MacOS nightly build.  Here is an error message from the build:
```
Traceback (most recent call last):
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python2.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 1324, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python2.7/site-packages/conda_build/render.py", line 735, in expand_outputs
    for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python2.7/site-packages/conda_build/metadata.py", line 2038, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python2.7/site-packages/conda_build/metadata.py", line 721, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python2.7/site-packages/conda_build/render.py", line 509, in finalize_metadata
    exclude_pattern)
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python2.7/site-packages/conda_build/render.py", line 393, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python2.7/site-packages/conda_build/render.py", line 359, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python2.7/site-packages/conda_build/render.py", line 143, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python2.7/site-packages/conda_build/environ.py", line 755, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: set(["libgfortran[version='>=4.0.0,<5.0.0.a0']", "libgfortran[version='>=3.0.1,<4.0.0.a0']"])
Exited with code 1
```
@doutriaux1 Do you have any insight on what is going on?

**Comment by mauzey1** [comment]
@doutriaux1 I think this might be related to this issue
https://github.com/conda-forge/hdf5-feedstock/issues/103

I am getting a similar dependency error when trying to make a build on my macbook.
```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - cdms2 -> esmf -> hdf5[version='>=1.10.4,<1.10.5.0a0'] -> libgfortran[version='>=3.0.1,<4.0.0.a0']
  - libgfortran[version='>=4.0.0,<5.0.0.a0']
```

**Comment by doutriaux1** [comment]
@mauzey1 I do remember running into this exact same issue. But I can't remember how I solved it.... I'll try to take a stab at this tomorrow. @dnadeau4 any idea? @mauzey1 does using `-c cdat/label/v1` instead of `-c cdat/label/nightly` help any?

**Comment by mauzey1** [comment]
@doutriaux1 Using -c cdat/label/v81 instead of -c cdat/label/nightly did not help with the error.

Also, sometimes the dependency conflict will involve Numpy.
```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - libgfortran[version='>=4.0.0,<5.0.0.a0']
  - numpy=1.14 -> libgfortran[version='>=3.0.1,<4.0.0.a0']
```

**Comment by doutriaux1** [comment]
@dnadeau4 I think (sigh) we need to recompile the macs to use conda newer `compiler("fortran")`
What do you think?
