### ISSUE TITLE
PrePARE import cmip6_cv error via conda

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmor#498]
Hi,
I did an update from cmor 3.3. to cmor 4.0 with
`conda update -c conda-forge cmor`
in order to run some PrePARE tests for some files. I tried commands that did work in the past:
`$PrePARE --table-path $tablepath $file`
but I get
```
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "/work/bm0021/miniconda2/envs/cmor/bin/PrePARE", line 11, in <module>
    load_entry_point('CMOR==3.4.0', 'console_scripts', 'PrePARE')()
  File "/work/bm0021/miniconda2/envs/cmor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/work/bm0021/miniconda2/envs/cmor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "/work/bm0021/miniconda2/envs/cmor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/work/bm0021/miniconda2/envs/cmor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/work/bm0021/miniconda2/envs/cmor/lib/python2.7/site-packages/cmip6_cv/__init__.py", line 1, in <module>
    from cmip6_cv.cmor_const import *
  File "/work/bm0021/miniconda2/envs/cmor/lib/python2.7/site-packages/cmip6_cv/cmor_const.py", line 1, in <module>
    import _cmip6_cv
ImportError: numpy.core.multiarray failed to import

```
Do you have an idea what went wrong? I think I need to reinstall it.
Best regards,
Fabi

**Comment by wachsylon** [comment]
I get the same error when I reinstall `cmor` in both the normal and nightly versions.
Is there a way to fix it in 
`work/bm0021/miniconda2/envs/cmor/lib/python2.7/site-packages/cmip6_cv/cmor_const.py`
by linking the correct file?

**Comment by mauzey1** [comment]
I'm not seeing this PrePARE numpy import issue with either the conda-forge or nightly version of CMOR.  I tried this on both a Mac and Linux machine.  I also tried installing CMOR 3.3.3 from conda-forge and then upgrading it to 3.4.0 (we don't have a version 4.0, yet).

When was your CMOR 3.3 installed?  Will it work if you try making a new conda environment with CMOR?

**Comment by wachsylon** [comment]
> 3.4.0 (we don't have a version 4.0, yet).
Sorry, 3.4 of course.

> When was your CMOR 3.3 installed? Will it work if you try making a new conda environment with CMOR?

I created a new env but it did not work. However, it worked on another machine and it seems that I am the only one having this issue. I will remove the old envs and try again next week.
