### ISSUE TITLE
OSX nightly build C compiler issue

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/cmor#511]
CMOR's OSX nightly build is not being built due to an error with the C compiler.
```
checking whether the C compiler works... no
configure: error: in `/Users/distiller/project/conda_build/cmor_1562609657582/work':
configure: error: C compiler cannot create executables
See `config.log' for more details
Traceback (most recent call last):
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 2313, in build_tree
    notest=notest,
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 1461, in build
    cwd=src_dir, stats=build_stats)
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python3.7/site-packages/conda_build/utils.py", line 397, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/distiller/project/workspace/test_macos_cmor/miniconda/lib/python3.7/site-packages/conda_build/utils.py", line 377, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/distiller/project/conda_build/cmor_1562609657582/work/conda_build.sh']' returned non-zero exit status 77.
Exited with code 1
```
@doutriaux1 @dnadeau4 Have you encountered this error?  Could you provide a solution?

**Comment by mauzey1** [comment]
Here's what seems to be culprit in the config.log when replicating the build on my macbook.
```configure:2656: checking whether the C compiler works
configure:2678: x86_64-apple-darwin13.4.0-clang -Wall -g -m64 -pipe -O2  -fPIC -I/Users/mauzey1/Desktop/cmor/conda_build/cmor_1562701942223/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include -L/Users/mauzey1/Desktop/cmor/conda_build/cmor_1562701942223/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib conftest.c  >&5
ld: library not found for -lSystem
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
```
