### ISSUE TITLE
Anaconda installation problems 

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#56]
When uninstalling CMOR2.9.2 after installing UV-CDAT from conda channel (to update to CMOR3) there is a dependency on UV-CDAT2.4.1

@dnadeau4 @doutriaux1 pinging you both here - it only seems to be an issue on ocean?

```
[duro@ocean ~]$ conda uninstall cmor
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: .........

Package plan for package removal in environment /export/durack1/anaconda2:

The following packages will be REMOVED:

    cmor:   2.9.2-PCMDI
    uvcdat: 2.4.1-UVCDAT
```

And also:
```
which python
/export/duro/anaconda2/bin/python
[duro@ocean ~]$ python
Python 2.7.11 |Anaconda custom (64-bit)| (default, Dec  6 2015, 18:08:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import cdms2
>>> import cmor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/duro/anaconda2/lib/python2.7/site-packages/cmor/__init__.py", line 1, in <module>
    from cmor_const import *
  File "/export/duro/anaconda2/lib/python2.7/site-packages/cmor/cmor_const.py", line 1, in <module>
    import _cmor
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /export/duro/anaconda2/lib/python2.7/site-packages/cmor/_cmor.so
```

**Comment by doutriaux1** [comment]
@dnadeau4 we will need to add the correct glibc dependency to your conda meta see: #1940

**Comment by doutriaux1** [comment]
@durack1 the dependency is normal, I hard coded the dependency in UV-CDAT 2.4.1 to cmor 2.9.2 because cmor 3 is not ready

**Comment by doutriaux1** [comment]
@durack1 which cmor gave you he error? 2.9.2 or 3.x?

**Comment by durack1** [comment]
@doutriaux1 
```
[duro@ocean ~]$ conda install cmor -c pcmdi
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......                     
Solving package specifications: .........             
Warning: 4 possible package resolutions (only showing differing packages):
  - jasper-1.900.1-UVCDAT.tar.bz2, ossuuid-1.6.2-UVCDAT.tar.bz2           
  - jasper-1.900.1-PCMDI.tar.bz2, ossuuid-1.6.2-UVCDAT.tar.bz2            
  - jasper-1.900.1-UVCDAT.tar.bz2, ossuuid-1.6.2-PCMDI.tar.bz2            
  - jasper-1.900.1-PCMDI.tar.bz2, ossuuid-1.6.2-PCMDI.tar.bz2             

Package plan for installation in environment /export/duro/anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    udunits-2.2.17             |            PCMDI         134 KB
    cmor-3.0beta1              |            PCMDI         1.2 MB
    ------------------------------------------------------------
                                           Total:         1.3 MB

The following NEW packages will be INSTALLED:

    cmor:    3.0beta1-PCMDI
    udunits: 2.2.17-PCMDI
```

**Comment by durack1** [comment]
It appears that using the following command line, I have `CMOR-3.0beta1` installed:
```
[durack1@ocean ~]$ conda create -n cmor -c pcmdi cmor -c uvcdat/label/nightly -c uvcdat
```

**Comment by durack1** [comment]
@dnadeau4 this is now solved
